services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: e7abdurakhman/taxi_bots
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/code/taxi_bot/static/
      - media_value:/code/taxi_bot/media/
      - logs_data:/var/log/taxi_bot/

  celery_worker:
    image: e7abdurakhman/taxi_bots
    restart: always
    volumes:
      - media_value:/code/taxi_bot/media/
      - logs_data:/var/log/taxi_bot/
    env_file:
      - ./.env
    command: bash -c 'cd taxi_bot; export DJANGO_SETTINGS_MODULE="taxi_bot.settings"; celery -A taxi_bot worker --loglevel=INFO'

  celery_beat:
    image: e7abdurakhman/taxi_bots
    restart: always
    depends_on:
      - celery_worker
    volumes:
      - ./celerybeat-schedule/:/code/celerybeat
      - media_value:/code/taxi_bot/media/
      - logs_data:/var/log/taxi_bot/
    env_file:
      - ./.env
    command: bash -c 'cd taxi_bot; export DJANGO_SETTINGS_MODULE="taxi_bot.settings"; celery -A taxi_bot beat --loglevel=INFO'


  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/www/media/
      - ./certbot/www:/var/www/certbot/:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./logs:/code/logs
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  driver_bot:
    image: e7abdurakhman/taxi_bots
    build:
      context: .
      dockerfile: DriverBotDispatcherDockerFile
    restart: always
    depends_on:
      - web
    volumes:
      - logs_data:/var/log/taxi_bot/
    env_file:
      - ./.env
    command: bash -c 'cd taxi_bot; export DJANGO_SETTINGS_MODULE="taxi_bot.settings"; python manage.py driver_bot'

  passenger_bot:
    image: e7abdurakhman/taxi_bots
    build:
      context: .
      dockerfile: PassengerBotDispatcherDockerFile
    restart: always
    depends_on:
      - web
    volumes:
      - logs_data:/var/log/taxi_bot/
    env_file:
      - ./.env
    command: bash -c 'cd taxi_bot; export DJANGO_SETTINGS_MODULE="taxi_bot.settings"; python manage.py passenger_bot'

volumes:
  postgres_data:
  redis_data:
  static_value:
  media_value:
  logs_data:
